name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Cambia a 'master' si tu rama principal se llama así

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Usa la versión estable de Flutter

      - name: Instalar dependencias
        run: flutter pub get

      - name: Compilar Flutter Web
        run: flutter build web --release --base-href "/expense-control-frontend/" --dart-define=API_BASE_URL=${{ vars.API_BASE_URL }}

      - name: Desplegar a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
