name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Cambia a 'master' si tu rama principal se llama así

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Usa la versión estable de Flutter

      - name: Instalar dependencias
        run: flutter pub get

      - name: Verificar si el secreto existe
        run: |
          if [ -z "${{ secrets.API_URL }}" ]; then
            echo "🚨 EL SECRETO ESTÁ VACÍO. GitHub no lo está leyendo."
            exit 1
          else
            echo "✅ El secreto se cargó correctamente."
          fi
          if [ -z "${{ secrets.GOOGLE_CLIENT_ID_WEB }}" ]; then
            echo "🚨 GOOGLE_CLIENT_ID_WEB está vacío."
            exit 1
          else
            echo "✅ GOOGLE_CLIENT_ID_WEB cargado."
          fi

      - name: Compilar Flutter Web
        run: |
          flutter build web --release --base-href "/" \
            --dart-define="API_BASE_URL=${{ secrets.API_URL }}" \
            --dart-define="GOOGLE_CLIENT_ID_WEB=${{ secrets.GOOGLE_CLIENT_ID_WEB }}"

      - name: Desplegar a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
